- name: Configure nginx
  hosts: nginx
  become: yes

  tasks:
  - name: Ensure nginx is present
    apt:
      name: nginx
      state: present
  
  - name: Editing index.html
    lineinfile:
      path: /var/www/html/index.html
      regexp: 'Weclome to Nginx!'
      line: '<p><script> document.write(new Date().toLocaleDateString()); </script></p>'
